[project]
name = "secure-data-encryption"
version = "0.1.0"
description = "Streamlit app for data encryption"
readme = "README.md"
requires-python = ">=3.8,<3.13"
dependencies = []

[tool.poetry]
package-mode = false
